version: "3.8"

services:
  alpha-motos-crm:
    image: docker.io/gustacg/alpha-motos-crm:latest
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        # Basic Traefik configuration
        - traefik.enable=true
        - traefik.http.routers.alpha-motos.rule=Host(`alphamotos.gustacg.com`)
        - traefik.http.routers.alpha-motos.entrypoints=websecure
        - traefik.http.routers.alpha-motos.tls=true
        - traefik.http.routers.alpha-motos.service=alpha-motos
        - traefik.http.services.alpha-motos.loadbalancer.server.port=80
        - traefik.http.services.alpha-motos.loadbalancer.passHostHeader=true

networks:
  network_swarm_public:
    external: true
    name: network_swarm_public
