// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyoelocsnouatoogkoyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95b2Vsb2Nzbm91YXRvb2drb3lnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjMyOTEsImV4cCI6MjA3MzUzOTI5MX0.5sZ6_Hr9HWDXOAnPQ8NxwLaNp_V7ctWmsW1-CXAnGuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});