name: Test Docker Secrets

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check secrets
      run: |
        echo "Testing Docker Hub secrets..."
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME secret is empty or missing"
        else
          echo "✅ DOCKER_USERNAME exists: ${{ secrets.DOCKER_USERNAME }}"
        fi
        
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "❌ DOCKER_PASSWORD secret is empty or missing"
        else
          echo "✅ DOCKER_PASSWORD exists (length: ${#{{ secrets.DOCKER_PASSWORD }}})"
          echo "✅ DOCKER_PASSWORD starts with: $(echo '${{ secrets.DOCKER_PASSWORD }}' | cut -c1-8)"
        fi
    
    - name: Test Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Success message
      run: echo "🎉 Docker Hub login successful!"
